EE-1225: Payment purse invariants
casper-network/casper-node pull request #1293
Opened 2021-04-09 15:35 UTC by mpapierski

Ref: https://casperlabs.atlassian.net/browse/EE-1225

This PR contains a regression test that tries to set a refund purse into a payment purse to violate `finalize_payment` postconditions. Fix consists of a check inside finalize_payment (rather than in set_refund_purse) to ensure we will not refund into the payment purse.

2021-04-12 16:28 UTC, henrytill commented on types/src/system/handle_payment/mod.rs
> +
Did you mean to commit this?

2021-04-16 16:21 UTC, henrytill requested changes
Holding until further notice

2021-07-14 23:00 UTC, dwerner approved these changes

2021-07-23 09:17 UTC, mpapierski commented
I'll re-run tests, and update the description with the error that this issue could cause

2021-07-27 11:13 UTC, Fraser999 approved these changes

2021-07-27 11:13 UTC, Fraser999 commented on execution_engine/CHANGELOG.md
> +* Fixed a case where user could potentially supply a refund purse as a payment purse.
```suggestion

### Fixed
* Fix a case where user could potentially supply a refund purse as a payment purse.

```

2021-07-27 11:13 UTC, Fraser999 commented on smart_contracts/contracts/test/ee-1225-regression/Cargo.toml
> +std = ["casper-contract/std", "casper-types/std"]
```suggestion
```

2021-07-30 09:10 UTC, Fraser999 approved these changes

2021-07-30 09:33 UTC, mpapierski commented
After removing the fix the regression test executes fine which means the code silently accepts refund purse as a payment purse which could lead to unexpected results once we'd change the refund percentage.

2021-07-30 09:33 UTC, mpapierski commented
bors r+

2021-07-30 10:26 UTC, merged