Move EE Shared Account Types Into `casper_types`.
casper-network/casper-node pull request #1810
Opened 2021-07-29 17:08 UTC by nilz3ro

:construction: WIP :construction:

2021-08-04 00:08 UTC, Fraser999 requested changes
The instances of `/// TODO: doc comment.` should be addressed.  Please liaise with @mpapierski on this.

2021-08-04 09:21 UTC, rafal-ch approved these changes
LGTM 👍

2021-08-04 15:57 UTC, mpapierski commented
> 
> 
> The instances of `/// TODO: doc comment.` should be addressed. Please liaise with @mpapierski on this.

@nilz3ro @Fraser999 Those items you moved out from a `shared` module into `casper_types` were ticketed for documenting as part of #1765. It should be possible for you to start document these in this PR, and as far as I'm concerned there will be no collision there (I'm documenting EE's core, and Dan started EE's storage IIRC). I'm sure you'll be able to move far, and we can sync up tomorrow and I can help you with remaining items.

2021-08-10 15:02 UTC, mpapierski approved these changes

2021-08-10 17:35 UTC, mpapierski commented
I think you should move last bits from https://github.com/nilz3ro/casper-node/blob/GH-1788/execution_engine/src/shared/account.rs and move it into types crate

2021-08-11 14:31 UTC, Fraser999 reviewed
Nitpicks only now.

2021-08-11 14:31 UTC, Fraser999 commented on execution_engine/src/shared/transform.rs
> +
Was this change necessary?

2021-08-11 14:31 UTC, Fraser999 commented on types/src/account.rs
> +    /// An Account constructor with presets for associated_keys and action_thresholds.
I think we should describe what the presets are - not necessarily in this first paragraph, but as a further paragraph.

2021-08-11 14:31 UTC, Fraser999 commented on types/src/account.rs
> +    /// Returns an [`AccessRights::ADD`]-only version of the [`URef`].
```suggestion
    /// Returns an [`AccessRights::ADD`]-only version of the main purse's [`URef`].
```

2021-08-11 14:31 UTC, Fraser999 commented on types/src/account.rs
> +    /// Verifies that removing the key will not cause the remaining weight to fall below any action
Maybe rephrase to something like "Returns an error if removing the key will cause the remaining weight ..."

I think an example of how thresholds work would be useful, particularly wrt to changing them.  Probably something in the top-level of this module.  The we could link to that from here and from the docs for `update_associated_key` and any others as relevant.

2021-08-11 14:31 UTC, Fraser999 commented on types/src/account.rs
> +    /// the key management threshold.
I'd rephrase to something like "Returns an error if the update would result in a violation of the key management thresholds."

Similar point for `set_action_threshold`.

2021-08-11 14:31 UTC, Fraser999 commented on types/src/account.rs
> +    /// Verifies if user can set action threshold
```suggestion
    /// Verifies if user can set action threshold.
```

2021-08-11 14:31 UTC, Fraser999 commented on types/src/account.rs
> +    /// Checks whether all authorization keys are associated with this account
```suggestion
    /// Checks whether all authorization keys are associated with this account.
```

2021-08-11 22:10 UTC, nilz3ro commented on execution_engine/src/shared/transform.rs
> +
No, I will undo this change.

2021-08-12 00:48 UTC, nilz3ro commented on types/src/account.rs
> +    /// Verifies that removing the key will not cause the remaining weight to fall below any action
I think a practical example with doctests would be great. Do you think the examples should be done as part of this PR or should we make a new issue to add some practical examples with doc tests?

2021-08-12 16:51 UTC, Fraser999 approved these changes

2021-08-12 17:48 UTC, nilz3ro commented
bors r+

2021-08-12 17:49 UTC, nilz3ro commented on types/src/account.rs
> +    /// Verifies that removing the key will not cause the remaining weight to fall below any action
Note for posterity: added #1905

2021-08-12 18:04 UTC, nilz3ro commented
bors r+

2021-08-12 19:01 UTC, merged