Added named dictionary convenience functions to the storage API.
casper-network/casper-node pull request #2171
Opened 2021-09-28 20:42 UTC by luis-casper

- EE-1225: Added regression test for the issue
- EE-1225: Fix finalize_payment
- EE-1229: Validate validator slots & validators.
- EE-1225: Remove commented out code
- Update types/src/system/auction/mod.rs
- EE-1229: Simplify test
- EE-1225: Fix cargofmt
- EE-1240: Move max associated keys into chainspec.
- EE-1240: Make max associated keys upgradable.
- EE-1240: Fix docs
- EE-1240: Bump all defaults to 100.
- EE-1240: Bump associated keys prices 10x
- EE-1226: Improve rustdocs on auction entrypoints.
- EE-1221: Increase create_purse/mint price 10x.
- EE-1221: Bump price to 2.5 tokens
- EE-1248: Basic test fixtures for ABI.
- EE-1248: Add generated transform variants.
- EE-1248: Fix transform serialization.
- EE-1248: Add CLI to generate example fixtures.
- EE-1248: Add generator for stored values.
- EE-1226: Apply review comments.
- EE-1221: Create purse first, then use in payment.
- EE-1221: Bump default create_purse cost.
- EE-1225: Remove commented out code
- EE-1221: Fix clipy issues.
- storage creates a subdir named after network.
- fix type.
- update Storage constructor; test
- test new storage constructor helpers.
- obey clippy.
- contract runtime now uses storage path directly.
- preserve io error.
- Update node/src/components/storage.rs
- begin working on PR feedback.
- Add EffectBuilder::get_consensus_validator_info.
- add logging for unexpected cases.
- improve error message.
- obey clippy.
- rpm package build for casper-client.
- NDRS-1608: Initial wire up of "query_global_state"
- Re-enable banning faulty validators
- Fix Clippy lint.
- Fail if there are slash items in the step request.
- Verify auction contract state in run_equivocator_network.
- NDRS-1608: Modify the client command arg
- NDRS-1608: Rename client command
- add keygen function to ffi.
- NDRS-1628: Initial legwork
- add ffi tests.
- update changelog.
- NDRS-1628: Create sealed_public_key module
- NDRS-1628: Address PR feedback
- fix changelog entry.
- choosing a direction for the tests.
- add test for invalid params.
- Move handle payment variant at the end
- wrapping up tests.
- removing ErrWrapper from tests.
- removing ErrWrapper.
- finish removing ErrWrapper.
- remove unused variable.
- implement lmdb manual flushing for EE
- add bench for native transfers and manual flushing
- add bench for native transfers and manual flushing
- remove outdated comment
- re-add deleted 1.2.0 lmdb fixture data
- add changelog entry
- Lift `async` from inner request to outside functions
- clean up secret_key_path.
- Minize client `main.rs` changes in branch
- Add a `CHANGELOG.md` entry for the client async changes
- check url if tagged version exists, otherwise use release
- disable auction upgrade test
- deduplicate parsing in client lib.
- rebalance stake and delegation weight to be similar to accounts.toml;  wait auction delay + 1
- Versioning CHANGELOG.md after 1.3.0 cut.
- Update TestContext to support new dictionary model
- Better Error:try_from tests
- Regenerating `Cargo.lock`
- EE-1225: Update changelog
- EE-1229: Update changelog
- EE-1240: Update changelog
- EE-1240: Cargo fmt
- EE-1226: Update changelog
- EE-1221: Update changelog
- EE-1248: Update changelog
- move to stable rust for all but casper-contract and smart contracts
- 1746: Fix incorrect schema representation for BlockIdentifier
- 1746: Update Changelog
- Versioning CHANGELOG.md after 1.3.0 cut.
- wrap deploy-accepted event stream event
- 1746: Address PR feedback
- Refactor ContractRuntime
- removed return unreachables added fromPublicKey and more
- Update smart_contracts/contract_as/assembly/key.ts
- remove print from panic in contract api and other nitpicks
- update changelog
- Update externals.ts
- fix clippy warnings
- Update CHANGELOG.md
- remove unused imports.
- temporarily disable upgrade tests
- Merge #1757
- Log the vertex when a doppelgänger is detected.
- Add own initial ping message immediately; don't interpret it as a doppelgänger's.
- add missing import.
- Count every unexpected ping as a doppelgänger.
- Add regression tests; fix has_ping.
- Update node/src/components/chainspec_loader.rs
- Ping only once per max-length round; fix tests.
- Fix wrong state hash being passed to the contract runtime
- rename maybe_target_account to target_account
- add timeout to delegation check
- Use the new ChainspecLoader::after_upgrade method
- parameterize sync timeout.
- update config examples.
- Re-enable the emergency upgrade tests
- Move the "No synchronization of the linear chain will be done" message to the LinearChainSync constructors.
- Revert "Use the new ChainspecLoader::after_upgrade method"
- Add a comment explaining the logic
- Re-enable the sync_upgrade_test
- replace TransferTarget with PublicKey.
- cleaning up FailedToParseInt and FailedToParseURef.
- finish cleaning up Error variants.
- clean up link text in doc comments.
- use PaymentStrParams.
- use SessionStrParams.
- revert to use fixed delay before including a deploy in a proposed block
- extract account_hash mod.
- fix overwriting issue in nctl bucket
- extract weight mod.
- extract action_type mod.
- extract error mod.
- Update pull_request_template.md
- remove AccountHashBytes.
- RPM build and publish to github tag for casper-client.
- Updated CHANGELOG.md.
- Correcting drone.yml duplicate step name
- 1608: Deprecate `state_get_item` from client
- 1608: Remove query-state from client binary
- fixing stuff that clippy found.
- Update execution_engine/CHANGELOG.md
- Update smart_contracts/contracts/test/ee-1225-regression/Cargo.toml
- Remove no longer maintained nix support
- Mention changes in changelog
- move an impl block.
- moving ee accounts to types crate.
- migrating Account to types/account.
- finish moving Account to types crate.
- Update node/CHANGELOG.md
- flush environment
- sync itst13 config with local
- address review comments
- Remove protocol data
- use cargo directly for audit target
- 1685: Address PR feedback
- 1685: Remove unnecessary query to global state
- add custom config for bonds_its nctl scenario
- temporarily disable tests
- Fix emergency upgrades tests after changes to storage paths
- begin migrating StoredValue to types crate.
- update import paths.
- fixing import paths.
- Re-enable the tests in nightly runs
- Port dial outcome logic fix from #1831.
- fixing import paths and stubbing out doc comments.
- fixes based on PR comments.
- Allow longer hex-strings to be displayed in jsons
- Refactor: Extract `find_hex_strings_longer_than` and add tests
- Update changelog of `casper-types`
- fix mistake made while merging dev.
- fix mistake made when merging dev.
- 1685: Return error instead of expecting
- 1685: Address PR feedback pt.2
- Apply suggestions from code review
- change static str to use constant.
- EE-1226: Rustfmt
- Update types/src/account/account_hash.rs
- Code review comments
- 1608: Add specificity to error message
- Restricting access to pub(crate)
- 1628: Address PR feedback
- 1685: Add error logging
- 1608: Resolve merge conflic
- GH-1768 - add documentation to storage, leverage pub(crate) to prune dead code
- uncomment compile_error! guard
- make tests pass
- Moving `mod`s before `use`s
- Importing `NonZeroUsize`
- Getting rid of unused announcements file
- cargo fmt
- rename parsing::get_target_account to parsing::parse_public_key.
- add some basic tests for Deploy::new_transfer.
- Add missing doccomment for `SubstringSpec::new()`
- EE-1226: Address @Fraser999 comments.
- Reduce chattiness of event dispatching and do not allocate a string on every event when at info or higher log level
- Add a `CHANGELOG.md` for tracing log changes
- Fix typos in documentation
- Reverting deleted compiler check
- Reverting Cargo.lock
- Add gov96 test.
- Get rid of unnecessary trait bounds on block_proposer
- No qualifying `std::time::Duration`
- Removed spurious comment
- Address review comments.
- assert deploy is transfer.
- 1608: Address PR feedback pt.3
- move test below impl
- 1608: Remove spurious im [...]

2021-10-29 15:53 UTC, Fraser999 requested changes
We need to add tests for these - probably in the form of a new test contract specifically for this and corresponding tests in execution_engine_testing/tests/src/test/contract_api

2021-11-01 21:45 UTC, luis-casper commented
> We need to add tests for these - probably in the form of a new test contract specifically for this and corresponding tests in execution_engine_testing/tests/src/test/contract_api

Done.

2021-11-15 13:35 UTC, Fraser999 approved these changes

2021-11-15 19:45 UTC, dwerner approved these changes

2021-11-25 14:07 UTC, luis-casper commented
bors r+

2021-11-25 16:49 UTC, merged