Purge deploys using latest block timestamp
casper-network/casper-node pull request #2217
Opened 2021-10-15 15:48 UTC by darthsiroftardis

CHANGELOG:

- Changed the pruning functionality in the `block_proposer` to use the timestamp of the latest finalized block as seen by the block proposer

Closes #2155

2021-10-16 12:45 UTC, afck reviewed
We should add checks to both call sites to make sure we only `propose_block_payload` if `request.context.timestamp() >= self.last_finalized_timestamp`, and otherwise `warn!`.
It's probably only relevant if our clock is wildly out of sync, but it's better to be safe and make sure we never propose an invalid block.

2021-10-16 12:45 UTC, afck commented on node/src/components/block_proposer.rs
> +                let pruned_hashes = self.prune(self.last_finalized_timestamp);
Should we get rid of the `PRUNE_INTERVAL` and `Event::Prune` now, and just prune whenever `last_finalized_timestamp` changes?

2021-10-19 09:15 UTC, rafal-ch approved these changes
LGTM

2021-10-20 14:22 UTC, darthsiroftardis commented on node/src/components/block_proposer.rs
> +                let pruned_hashes = self.prune(self.last_finalized_timestamp);
Removed `Event::Prune`

2021-10-20 14:26 UTC, goral09 approved these changes

2021-10-20 14:37 UTC, afck commented on node/src/components/block_proposer.rs
> +                    Effects::new()
We should log a warning here. It probably means that a block request spent so much time in the reactor queue (or in the block proposer queue?) that in the meantime we finalized a block with a timestamp newer than this.

2021-10-20 14:37 UTC, afck commented on node/src/components/block_proposer.rs
> +                let pruned_count = pruned_hashes.total_pruned;
Do we know how fast pruning is? I wonder whether we should have a minimum delay, e.g. something like: if we already pruned within the last minute, don't prune again? But maybe it's not needed.

2021-10-20 14:39 UTC, darthsiroftardis commented on node/src/components/block_proposer.rs
> +                    Effects::new()
@afck Do you have an idea of what the log message should be like,

"block request timestamp is behind the timestamp of the last finalized block"?

2021-10-21 08:42 UTC, afck commented on node/src/components/block_proposer.rs
> +                    Effects::new()
Yes, sounds good. Maybe add something like: "not proposing a block; relevant deploys might have been purged"

2021-12-07 01:51 UTC, Fraser999 requested changes
As discussed, this PR should include tests for this change.

2022-01-15 20:19 UTC, goral09 commented
@Fraser999 @darthsiroftardis , Do we plan on including this PR with 1.5.0 release?

2022-05-16 15:40 UTC, closed without merging