Fix from_bytes for WriteBid and WriteWithdraw variants of Transform
casper-network/casper-node pull request #2649
Opened 2022-02-05 08:00 UTC by SamuelSchlesinger

## Fix FromBytes for WriteBid and WriteWithdraw variants of Transform

Currently, if you attempt to decode previously encoded WriteBid and WriteWithdraw variants of Transform, it would fail with a `bytesrepr::Error::Formatting` error. This commit properly decodes them, and introduces a convention for doing so in the future.

2022-02-05 09:51 UTC, goral09 commented on types/src/execution_result.rs
> +// not.
We will most likely be getting rid of `Op`-like types and operations so it's fine to not put more work into combining them.

2022-02-08 13:51 UTC, Fraser999 approved these changes
Approved assuming the suggested change is applied (this should fix the CI failure I believe).

Nice work :+1:

2022-02-08 13:51 UTC, Fraser999 commented on types/src/execution_result.rs
> +use std::convert::TryFrom;
```suggestion
use core::convert::TryFrom;
```

2022-02-08 13:52 UTC, Fraser999 commented on types/src/execution_result.rs
> +// not.
As Mateusz hints, this todo could safely be removed.

2022-02-08 16:21 UTC, Fraser999 requested changes
I just noticed a bug in the PR.  Blocking pending the fix.

2022-02-08 16:21 UTC, Fraser999 commented on types/src/execution_result.rs
>              | Transform::WriteContractPackage => U8_SERIALIZED_LENGTH,
```suggestion
            | Transform::WriteContractPackage => 0,
```

2022-02-10 17:47 UTC, SamuelSchlesinger commented
> I just noticed a bug in the PR. Blocking pending the fix.

Merged your suggested change -- good catch. The CI stuff seems to be a repeated problem where my local toolchain is different from the one in CI, not sure what I should do to systematically fix it but I've been reading the CI scripts and invoking bits of them locally as my intermediate fix.

2022-02-10 17:48 UTC, SamuelSchlesinger commented on types/src/execution_result.rs
> +// not.
Thank you!

2022-02-21 17:27 UTC, Fraser999 approved these changes

2022-02-22 13:17 UTC, SamuelSchlesinger commented
bors r+

2022-02-22 14:06 UTC, merged