Update json-rpc to avoid some breaking changes
casper-network/casper-node pull request #3181
Opened 2022-07-07 11:30 UTC by Fraser999

This PR updates the `casper-json-rpc` crate to avoid some breaking changes in the node JSON-RPC server.

Specifically:
* it allows the `params` field to be null, interpreting that as an empty array, or equivalently, a `None` value
* it relaxes the range of error codes for which it supports creating an error response, since we currently use reserved values
* it can be configured to ignore extra fields provided in JSON-RPC requests (our usage in node configures the server to ignore extra fields as per current behaviour)

Closes #3175.

2022-07-07 12:07 UTC, georgepisaltu reviewed
Looks good, a couple of comments.

2022-07-07 12:07 UTC, georgepisaltu commented on json_rpc/src/error.rs
> +    /// and -32100 inclusive.
The specification states "The error codes from and including -32768 to -32000 are reserved for pre-defined errors", with `-32099` to `-32000` being "reserved for implementation-defined server-errors". I think this doc comment is ambiguous in this sense. Maybe if we added the bit about implementation-defined server-errors, it would be better.

2022-07-07 12:07 UTC, georgepisaltu commented on json_rpc/src/request/params.rs
> +            Value::Null => Ok(Params::Array(vec![])),
I think we should also mark this as deprecated right now so that in the major upcoming release we can safely delete this custom logic. I was thinking about logging this, but it doesn't make sense in an RPC context, we would have to let the users know in the RPC response. Maybe it would just be enough to mention this in the changelog, let me know what you think.

2022-07-07 13:17 UTC, Fraser999 commented on json_rpc/src/request/params.rs
> +            Value::Null => Ok(Params::Array(vec![])),
It's not a change when compared to the currently-published version, but looking at the changelog, I need to update it to cover the changes here.

2022-07-07 13:18 UTC, Fraser999 commented on json_rpc/src/error.rs
> +    /// and -32100 inclusive.
Done in [e0ecbc1](https://github.com/casper-network/casper-node/pull/3181/commits/e0ecbc1a351833231595c0bc9ef6e580fee30532).

2022-07-07 13:18 UTC, Fraser999 commented on json_rpc/src/request/params.rs
> +            Value::Null => Ok(Params::Array(vec![])),
Done in [e0ecbc1](https://github.com/casper-network/casper-node/pull/3181/commits/e0ecbc1a351833231595c0bc9ef6e580fee30532).

2022-07-07 13:29 UTC, goral09 approved these changes

2022-07-07 13:32 UTC, rafal-ch requested changes
Blocking temporarily since I have strange readings from `casper-test`. I'll unlock asap.

2022-07-07 13:38 UTC, georgepisaltu approved these changes
LGTM

2022-07-07 13:40 UTC, rafal-ch commented
> Blocking temporarily since I have strange readings from `casper-test`. I'll unlock asap.

I used `casper-test` version that predates the alignment with RPC server changes.

I checked the `rpc_jsonrpc_error_codes.rs` test on `1.4.6` and it's passing correctly. On your branch, though, it fails with:
```
errors="'non_existing' is not a supported json-rpc method on this server" is not of type "null"
```

I'm unblocking the PR right now as I see no other issues. I'f your ok with the above, I think it's good to go as is.

2022-07-07 13:41 UTC, rafal-ch approved these changes
LGTM with [single comment](https://github.com/casper-network/casper-node/pull/3181#issuecomment-1177632523) that might be worth checking.

2022-07-07 14:19 UTC, Fraser999 commented
bors merge

2022-07-08 16:18 UTC, Fraser999 commented
bors merge

2022-07-08 17:03 UTC, merged