537 AssemblyScript Counter Contract READMEs
casper-network/casper-node pull request #3202
Opened 2022-07-11 17:22 UTC by ACStoneCL

### Related links

[Document Assembly script based Counter contract #537](https://github.com/casper-network/docs/issues/537)

### Changes

Adding readme files that explain the example contracts related to the "Counter" in AssemblyScript

2022-07-12 16:53 UTC, ACStone-MTS commented
@mpapierski When you get a chance, could you take a look and see if I missed anything glaring here?

2022-07-14 16:25 UTC, darthsiroftardis requested changes
I believe the READMEs have been interchanged, once that correction has been made, I can approve

2022-07-14 16:25 UTC, darthsiroftardis commented on smart_contracts/contracts_as/example/increment-counter/README.md
> +We will also define the `Call` function that will start the code execution and perform the actual code installation. This function initializes the contract by setting the counter to 0 and creates `Na
```suggestion
We will also define the `Call` function that will start the code execution and perform the contract installation. This function initializes the contract by setting the counter to 0 and creates `NamedKeys` in the current context. Specifically, it creates the keys `counter_package_name` and `counter_access_uref`.
```

2022-07-14 16:25 UTC, darthsiroftardis commented on smart_contracts/contracts_as/example/increment-counter/README.md
> +We will also define the `Call` function that will start the code execution and perform the actual code installation. This function initializes the contract by setting the counter to 0 and creates `Na
Also some changes around the wording of creating NamedKeys, I'd rather we say we create the NamedKeys to pass them along to the contract where they are persisted within the contracts context.

2022-07-14 17:14 UTC, darthsiroftardis approved these changes

2022-07-15 14:47 UTC, darthsiroftardis commented
bors r+

2022-07-15 14:59 UTC, ipopescu approved these changes
Wonderful to have this!

2022-07-15 15:35 UTC, merged