Added readme file for the hello world example
casper-network/casper-node pull request #3217
Opened 2022-07-26 10:30 UTC by GloreenS

### Related Links
Card [536](https://github.com/casper-network/docs/issues/536)

### Changes
Added readme file for the hello world assembly script contract.

2022-07-27 13:34 UTC, ACStoneCL approved these changes
Content looks great to me! Just some small consistency suggestions.

2022-07-27 13:34 UTC, ACStoneCL commented on smart_contracts/contracts_as/example/hello-world/README.md
> +The tests start by initializing the casper crates and creating a genesis account. Then the contract Wasm is loaded and the deploy_item object is created. The deploy_item object is passed to the execu
```suggestion
The tests start by initializing the Casper crates and creating a genesis account. Then the contract Wasm is loaded and the deploy_item object is created. The deploy_item object is passed to the execute_request. Finally, the execution engine is invoked to process the execute_request. 
```

2022-07-27 13:34 UTC, ACStoneCL commented on smart_contracts/contracts_as/example/hello-world/README.md
> +Make a note of the NamedKey uref hash in the faucet account details.
```suggestion
Make a note of the NamedKey URef hash in the faucet account details.
```

2022-07-27 13:34 UTC, ACStoneCL commented on smart_contracts/contracts_as/example/hello-world/README.md
> +You can view the value stored in the NamedKey by using the uref hash assigned to the NamedKey. To do this, we will first find the state root hash of the network using the following command:
```suggestion
You can view the value stored in the NamedKey by using the URef hash assigned to the NamedKey. To do this, we will first find the state root hash of the network using the following command:
```

2022-07-27 13:34 UTC, ACStoneCL commented on smart_contracts/contracts_as/example/hello-world/README.md
> +Then use the uref hash and the state root hash to view the value stored in the NamedKey.
```suggestion
Then use the URef hash and the state root hash to view the value stored in the NamedKey.
```

2022-08-03 16:31 UTC, TomVasile requested changes

2022-08-03 16:31 UTC, TomVasile commented on smart_contracts/contracts_as/example/hello-world/README.md
> +:::note
typo?

2022-08-03 16:39 UTC, GloreenS commented on smart_contracts/contracts_as/example/hello-world/README.md
> +:::note
updated style

2022-08-03 16:41 UTC, merged