GH-3268: Add support for CA signed client certificates
casper-network/casper-node pull request #3291
Opened 2022-08-25 15:14 UTC by mpapierski

Closes #3268

This commit introduces an option to load a node's identity from existing certificates signed by a CA authority. This is optional and is helpful for some private chains, where joining new nodes to an existing private network is a restricted process.

# Config

There is a new configuration option in `config.toml.`

```toml
[network.identity]
tls_certificate = "node_cert.pem"
secret_key = "node.pem"
ca_certificate = "ca_cert.pem"
```

The node will load the existing secret key, certificate, and CA cert at startup if specified.

When new peer nodes are connecting, the node process will validate peer client certificates against provided CA certificates and rejects those not signed by provided CA.

# Testing

Script that generates `ca_key.pem` `ca_cert.pem` and bunch of `local_node*.pem` certificates signed by CA

https://gist.github.com/mpapierski/bd80f7519f697daa0337e27f44d81b89

Connecting with a `openssl s_client` with client key signed by a different CA cert to a nctl network using shared ca_cert.pem:

```
2022-08-25T14:39:34.127048Z DEBUG init:incoming{; peer_addr=127.0.0.1:55958}: [casper_node::components::small_network small_network.rs:478] incoming connection failed early; err=TLS validation error of peer certificate: the certificate is not signed by provided certificate authority
```

Otherwise, a network reaches consensus if every node in the network is set up with shared CA.

2022-08-26 13:01 UTC, marc-casperlabs requested changes
Formally, this is missing `CHANGELOG.md` entries and documentation for this new feature (/cc @Fraser999 -- into the `README.md`?)

Other than that, I think the only blockers are the repeated code in cert validation and the integration of the CA cert into the `SmallNetworkIdentity`.

2022-08-26 13:01 UTC, marc-casperlabs commented on node/src/components/small_network.rs
> +        ca_certificate: Option<X509>,
I don't think we want to tie the CA certificate into the small network identity here. It should just be known to the networking component, unless I am missing something?

If we're loading them from a file, I don't think we need to validate them upon loading in `SmallNetworkIdentity`.

2022-08-26 13:01 UTC, marc-casperlabs commented on node/src/components/small_network.rs
> +            our_ca: small_network_identity.ca_certificate,
I think this should be named `network_ca`, since it is shared across all nodes in the network.

2022-08-26 13:01 UTC, marc-casperlabs commented on node/src/reactor/initializer.rs
> +        let network_config = config.map_ref(|cfg| cfg.network.clone());
Just :golfing_man: , but could this be

```rust
let small_network_identity = config.map_ref(|cfg| SmallNetworkIdentity::from_config(&cfg.network));
```

?

2022-08-26 13:01 UTC, marc-casperlabs commented on node/src/tls.rs
> +    // TODO: It might be that we need to call `PKey::private_key_from_pkcs8` instead.
Can you elaborate on this? :)

2022-08-26 13:01 UTC, marc-casperlabs commented on node/src/tls.rs
> +    // Check expiration times against current time.
If this code copy&pasted from the other validation function, can we factor it out or merge these two, so we DRY here?

2022-08-26 13:01 UTC, marc-casperlabs commented on node/src/tls.rs
> +        let issuer = mkname("US", "Casper Blockchain", "node-0").unwrap();
`"node-0"` is probably not a good issuer name here. How about `"network"` or `"network-ca"`?

Minor though, since it is just testing code.

2022-08-29 15:18 UTC, mpapierski commented on node/src/tls.rs
> +    // TODO: It might be that we need to call `PKey::private_key_from_pkcs8` instead.
I don't have more context on that. It's copy pasted from here. I can remove it if it's outdated?

https://github.com/casper-network/casper-node/blob/f7bc8b64630ec871f3c2219d646bdc7ebc91dbd9/node/src/tls.rs#L546-L551

2022-08-29 15:42 UTC, mpapierski commented on node/src/reactor/initializer.rs
> +        let network_config = config.map_ref(|cfg| cfg.network.clone());
Applied

2022-08-29 16:44 UTC, marc-casperlabs commented on node/src/tls.rs
> +    // TODO: It might be that we need to call `PKey::private_key_from_pkcs8` instead.
Touché.

IIRC, I was not sure about the storage format of the private key. We can remove the comment.

2022-08-30 07:38 UTC, mpapierski commented on node/src/reactor/initializer.rs
> +        let network_config = config.map_ref(|cfg| cfg.network.clone());
Actually, not. `SmallNetworkIdentity::from_config` returns `Result` and `config.map_ref` returns `WithDir<T>` so it's a bit cumbersome to work with

2022-08-30 13:13 UTC, mpapierski commented on node/src/tls.rs
> +        let issuer = mkname("US", "Casper Blockchain", "node-0").unwrap();
Applied (used `Casper Network`)

2022-08-30 13:13 UTC, mpapierski commented on node/src/tls.rs
> +    // Check expiration times against current time.
Tried my best to DRY as much as possible

2022-08-30 13:14 UTC, mpapierski commented on node/src/tls.rs
> +    // TODO: It might be that we need to call `PKey::private_key_from_pkcs8` instead.
Removed

2022-08-30 13:14 UTC, mpapierski commented on node/src/components/small_network.rs
> +            our_ca: small_network_identity.ca_certificate,
Renamed

2022-08-30 13:14 UTC, mpapierski commented on node/src/components/small_network.rs
> +        ca_certificate: Option<X509>,
Removed in favor of loading network_ca in a network component

2022-08-31 12:24 UTC, marc-casperlabs approved these changes
Looks good to me :)

2022-09-01 12:27 UTC, mpapierski commented
bors r+

2022-09-01 14:37 UTC, mpapierski commented
bors r+

2022-09-01 16:21 UTC, mpapierski commented
bors r+

2022-09-01 17:00 UTC, merged