Vendoring pwasm-utils 0.16 under the name wasm-utils
casper-network/casper-node pull request #3760
Opened 2023-03-14 16:15 UTC by Boiethios

The `pwasm-utils` crate is not maintained anymore (the repository is archived), so this commit vendors it under the name `wasm-utils`. The code is simplified as well, with the ability to use `no-std` being removed since it is not used in the `execution_engine` crate.

2023-03-15 15:08 UTC, rafal-ch commented on wasm-utils/src/export_globals.rs
> +#[cfg(test)]
I think we need to update our `Makefile` to include these tests in the `test-rs` job.

2023-03-16 18:38 UTC, Fraser999 requested changes
I'd prefer if this weren't added as a new crate, but rather as a module inside EE.

If we do want to stick with making this a crate, we'll need to make a few more changes to support that.

I'll block the PR until we get a decision since it shouldn't merge as is.

2023-03-21 16:07 UTC, RitaMAllenCA commented
new name: casper-pwasm-utils

2023-03-28 13:49 UTC, Boiethios commented
PR no more relevant since it's now forked and lives in its own repo.

2023-03-28 13:49 UTC, closed without merging