`bytesrepr` networking protocol
casper-network/casper-node pull request #3799
Opened 2023-03-27 12:07 UTC by marc-casperlabs

Closes #2944.

This PR makes `bytesrepr` the encoding for all network traffic except the handshake in 1.6. It includes some handwritten implementations for select types that required them or are included in `casper-types`:

* `Arc<T>`
* `Box<T>`
* `Box<[u8]>`
* `FinalitySignature`
* `u128`
* `SocketAddr`
* `SocketAddrV4`
* `SocketAddrV6`
* `Ipv4Addr`
* `Ipv6Addr`

For all other types found in the node, a new crate for deriving `FromBytes`/`ToBytes` has been added. The affected types are:

* `protocol::Message`
* `ConsensusMessage`
* `ConsensusValue`
* `EraMessage<C>`
* `zug::Message<C>`
* `SyncResponse`
* `Proposal<C>`
* `BlockPayload` 
* `DeployHashWithApprovals`
* `fetcher::Tag`
* `gossiper::message::Message`
* `GossipedAddress`
* `ConsensusRequestMessage`
* `EraRequest<C>`
* `SyncRequest<C>`
* `HighwayMessage<C>`
* `Vertex<C>`
* `SignedWireUnit<C>`
* `HashedWireUnit<C>`
* `WireUnit<C>`
* `ValidatorMap<T>`
* `Observation<C>`
* `ValidatorIndex`
* `SignedMessage<C>`
* `Content<C>`
* `IndexObservation`
* `Dependency<C>`
* `Ping<C>`
* `Endorsements<C>`
* `Evidence<C>`
* `SignedEndorsement<C>`
* `Endorsement<C>`
* `FinalitySignatureId`
* `SignatureWrapper`
* `network::Message<P>`
* `network::tests::Message`
* `Nonce`
* `ConsensusCertificate`

The only other change to the `bytesrepr` proper was enabling of cross-crate inlining for primitive types.

2023-04-12 12:08 UTC, Fraser999 reviewed
It'd be good to have `Serialize` and `Deserialize` stripped from whichever types no longer need those traits.  Seems like it would be most of the ones where we added the new traits?

2023-04-12 12:08 UTC, Fraser999 commented on Cargo.toml
> -debug = true
Did you mean to include this change?

2023-04-12 12:08 UTC, Fraser999 commented on Cargo.toml
Since you're adding a new crate here, it should be included in the casper_updater tool.

2023-04-12 12:08 UTC, Fraser999 commented on bytesrepr_derive/Cargo.toml
> +name = "bytesrepr_derive"
```suggestion
name = "casper-bytesrepr-derive"
```

2023-04-12 12:08 UTC, Fraser999 commented on types/src/bytesrepr.rs
> +impl ToBytes for u128 {
I see this was added as `u128`s are used in some Zug messages, but I think we need to discuss whether we want to add support for this, or change the messages to use the existing `U128` type, or perhaps change the encoding for `u128` to match `U128`.

2023-04-12 12:08 UTC, Fraser999 commented on types/src/bytesrepr.rs
> +
Seems like we don't need to add support for `i128` at all?

2023-04-12 12:08 UTC, Fraser999 commented on types/src/bytesrepr.rs
> +    impl ToBytes for Ipv4Addr {
Could we group the impls so that we have pairs of `ToBytes` then `FromBytes` for each type pls?  It's easier to check that the decoding matches the encoding.

2023-04-12 12:08 UTC, Fraser999 commented on types/src/bytesrepr.rs
> +                    writer.push(0u8);
Let's make the tags `pub const` values please so they're publicly accessible (similar to the tags for `Option` and `Result`).

Same point for the `Either` impl below.

2023-04-12 12:08 UTC, Fraser999 commented on types/src/bytesrepr.rs
> +
A few of these tests have an extra blank line before the closing brace.

2023-04-12 12:08 UTC, Fraser999 commented on types/src/bytesrepr.rs
> +                v6.set_scope_id(0);
Can you add an explanatory comment to the code as to why this is needed pls?

2023-04-13 20:37 UTC, EdHastingsCasperLabs requested changes
i want to discuss this before we move forward

2023-04-20 09:18 UTC, marc-casperlabs commented
Closing this as discussed, to be resurrected in a different PR.

2023-04-20 09:18 UTC, closed without merging