Update branding and company name #3660
casper-network/casper-node pull request #3837
Opened 2023-04-12 13:01 UTC by 0xE69

Uploaded new branding images. 
Updated html_favicon_url & html_logo_url
Updated "CasperLabs" to "Casper Labs" in documentation. 

https://github.com/casper-network/casper-node/issues/3660

No Known issues.

2023-04-12 23:26 UTC, RitaMAllenCA commented
@piotr-dziubecki Is this someone from one of your project teams? Please advise so we can get this merged, thanks

2023-04-13 12:54 UTC, piotr-dziubecki reviewed
changes look good to me

2023-04-13 20:27 UTC, EdHastingsCasperAssociation commented on resources/test/rpc_schema_hashing.json
> +                "description": "A Casper Labs value.",
```suggestion
                "description": "An instance of any valid variant of StoredValue.",
```

2023-04-13 20:28 UTC, EdHastingsCasperLabs commented on node/src/types/json_compatibility/stored_value.rs
> +    /// A Casper Labs value.
```suggestion
    /// An instance of any variant of CLValue.
```

2023-04-13 20:31 UTC, EdHastingsCasperLabs approved these changes

2023-04-27 09:15 UTC, rafal-ch commented
Merging [this one](https://github.com/0xE69/casper-node/pull/1) should fix the build.

2023-06-01 13:06 UTC, ACStoneCL commented
@0xE69 Is there anything blocking this merge on your end, [other than this build fix](https://github.com/0xE69/casper-node/pull/1)?

2023-06-12 19:48 UTC, MParlikar requested changes
The Association owns the software, instances referring to Labs, for the most part should be updated to refer to the Association, references to the tech, should state just 'Casper' where possible.  License is Apache 2.0

2023-06-12 19:48 UTC, MParlikar commented on ci/build_client_rpm.sh
> +# Images used in this script are build in Casper Labs/buildenv repo
Should just say 'Casper' not Casper Labs

2023-06-12 19:48 UTC, MParlikar commented on ci/casper_updater/Cargo.toml
> +description = "A tool to update versions of all published Casper Labs packages."
Should say just 'Casper' - Not Casper Labs actually.

2023-06-12 19:48 UTC, MParlikar commented on ci/casper_updater/README.md
> +A tool to update versions of all published Casper Labs packages.
Same here - Casper

2023-06-12 19:48 UTC, MParlikar commented on ci/casper_updater/README.md
> +The tool iterates through each published Casper Labs package, asking for a new version for each or automatically bumping the major, minor or patch version if `--bump=[major|minor|patch]` was specifie
Just remove Casper Labs all together here.

2023-06-12 19:48 UTC, MParlikar commented on ci/casper_updater/src/dependent_file.rs
> +/// A file which is dependent on the version of a certain Casper Labs crate.
Rename to Casper

2023-06-12 19:48 UTC, MParlikar commented on ci/casper_updater/src/main.rs
> +//! A tool to update versions of all published Casper Labs packages.
rename to Casper

2023-06-12 19:48 UTC, MParlikar commented on ci/casper_updater/src/package.rs
> +/// Represents a published Casper Labs crate or AssemblyScript package which may need its version
re label to 'Casper'

2023-06-12 19:48 UTC, MParlikar commented on docker_make.sh
> +# Images used in this script are build in Casper Labs/buildenv repo
Rename to 'Casper'

2023-06-12 19:48 UTC, MParlikar commented on execution_engine/Cargo.toml
> +description = "Casper Labs execution engine crates."
Rename to 'Casper'

2023-06-12 19:48 UTC, MParlikar commented on execution_engine/README.md
> +The main component of the Casper Labs Wasm execution engine.
Rename to 'Casper'

2023-06-12 19:48 UTC, MParlikar commented on execution_engine/src/lib.rs
> +    html_logo_url = "https://raw.githubusercontent.com/casper-network/casper-node/blob/dev/images/CasperLabs_Logo_Favicon.png",
Can we put the Casper logo here?  The source code is owned by Casper Assocation, not Labs.

2023-06-12 19:48 UTC, MParlikar commented on execution_engine_testing/test_support/src/lib.rs
> +    html_logo_url = "https://raw.githubusercontent.com/casper-network/casper-node/blob/dev/images/CasperLabs_Logo_Favicon.png",
Can we put the Casper logo here?  The source code is owned by Casper Assocation, not Labs.

2023-06-12 19:48 UTC, MParlikar commented on node/src/components/consensus/cl_context.rs
> +/// The collection of types used for cryptography, IDs and blocks in the Casper Labs node.
Casper

2023-06-12 19:48 UTC, MParlikar commented on node/src/components/rpc_server/rpcs/docs.rs
> +        name: "Casper Labs Open Source License Version 1.0".to_string(),
Casper

2023-06-12 19:48 UTC, MParlikar commented on node/src/components/rpc_server/rpcs/docs.rs
> +            name: "Casper Labs Open Source License Version 1.0".to_string(),
The license should be Apache 2.0 - not COSL

2023-06-12 19:48 UTC, MParlikar commented on node/src/lib.rs
> +    html_logo_url = "https://raw.githubusercontent.com/casper-network/casper-node/blob/dev/images/CasperLabs_Logo_Favicon.png",
Casper Association

2023-06-12 19:48 UTC, MParlikar commented on resources/test/rpc_schema_hashing.json
> +          "name": "Casper Labs Open Source License Version 1.0",
This should be Apache 2.0

2023-06-12 19:48 UTC, MParlikar commented on smart_contracts/contract/src/lib.rs
> +    html_logo_url = "https://raw.githubusercontent.com/casper-network/casper-node/blob/dev/images/CasperLabs_Logo_Favicon.png",
Casper Association

2023-06-12 19:48 UTC, MParlikar commented on types/src/lib.rs
> +    html_logo_url = "https://raw.githubusercontent.com/casper-network/casper-node/blob/dev/images/CasperLabs_Logo_Favicon.png",
Casper Association

2023-08-17 17:17 UTC, closed without merging