Fix stuck historical sync on legacy deploys without approvals
casper-network/casper-node pull request #3981
Opened 2023-05-24 10:09 UTC by rafal-ch

This PR loosens the validation criteria for the `LegacyDeploy` fetcher and provides a NCTL test to prove that 1.5+ nodes are not stuck when syncing block with deploy which has no approvals.

Closes https://github.com/casper-network/casper-node/issues/3976

2023-05-24 13:22 UTC, rafal-ch commented
bors try

2023-05-25 12:47 UTC, Fraser999 requested changes
Partial review for now.

2023-05-25 12:47 UTC, Fraser999 commented on node/src/types/deploy/legacy_deploy.rs
> +            .clone()
I think we should avoid this, since we could set the inner Deploy's `is_valid` field to `Ok` and then extract the inner Deploy via the `From` impl below, yielding a Deploy which claims to be valid, but might not be.

Instead, we could just call `self.0.has_valid_hash()` inside `fn validate` and remove this `impl LegacyDeploy` altogether.

2023-05-25 13:33 UTC, rafal-ch commented on node/src/types/deploy/legacy_deploy.rs
> +            .clone()
Good catch!
I'll update after considering if we might want to have another `is_valid` cell on the `LegacyDeploy` itself.

2023-05-25 15:18 UTC, rafal-ch commented on node/src/types/deploy/legacy_deploy.rs
> +            .clone()
The `LegacyDeploy::validate()` is called 3 times per deploy; taking into consideration that `has_valid_hash()` is pretty cheap call, we'll go with the simple solution suggested by @Fraser999.

Updated 1b344ac3b6a399e60ed7593772cc8c51e4600e1d.

2023-05-30 10:43 UTC, Fraser999 approved these changes

2023-05-30 11:59 UTC, rafal-ch commented
bors r+

2023-05-30 13:54 UTC, rafal-ch commented
bors r+

2023-05-30 15:26 UTC, merged