Updates toolchain to a more recent 2023-03-25
casper-network/casper-node pull request #4008
Opened 2023-06-01 12:57 UTC by mpapierski

This bumps a toolchain for contract API to more recent 2023-03-25. This is not the most recent, as the current nightly appears to produce non-mvp WebAssembly opcodes which are not supported on our platform. Apparently this version update also decerases gas cost on average in our tests.

See also upstream compiler issue here: https://github.com/rust-lang/rust/issues/109807

2023-06-01 13:20 UTC, gRoussac approved these changes

2023-06-01 13:56 UTC, rafal-ch approved these changes
LGTM :+1:

2023-06-01 14:30 UTC, Fraser999 requested changes

2023-06-01 14:30 UTC, Fraser999 commented on execution_engine_testing/tests/src/test/explorer/faucet.rs
> +    const EXPECTED_FAUCET_CALL_BY_USER_COST: u64 = 3_242_199_690;
As per the comment above these consts, could you update the table in the indicated README too please?

2023-06-01 15:42 UTC, mpapierski commented on execution_engine_testing/tests/src/test/explorer/faucet.rs
> +    const EXPECTED_FAUCET_CALL_BY_USER_COST: u64 = 3_242_199_690;
Done

2023-06-01 17:48 UTC, Fraser999 approved these changes

2023-06-02 09:49 UTC, mpapierski commented
bors r+

2023-06-02 11:17 UTC, merged