Update changelogs for 1.5.4
casper-network/casper-node pull request #4385
Opened 2023-10-27 14:27 UTC by jacek-casper

The changelog here is pretty detailed, let me know if something can be removed, I opted on the side of keeping things in. Also added PR numbers, but I can remove them if we don't want them.

2023-10-31 18:40 UTC, MParlikar reviewed
Is there a changelog for the chainspec? The gas table + block times are also changing.

2023-11-01 10:50 UTC, jacek-casper commented
@MParlikar there is no changelog for the chainspec AFAIK, but we could add it under the execution engine, because that's where the opcode costs are used (and the PR actually changed the default costs there too: https://github.com/casper-network/casper-node/pull/4387/files)

2023-11-02 12:28 UTC, alsrdn requested changes

2023-11-02 12:28 UTC, alsrdn commented on execution_engine/CHANGELOG.md
> +* Add initial support for private chain (#3106).
It would be good here to unwrap the new chainspec parameters added with the private chain changes since they are user facing.

2023-11-02 12:28 UTC, alsrdn commented on execution_engine/CHANGELOG.md
> +* Fix an issue where payment errors penalty could've been paid to block proposer regardless of fee_handling/refund_handling option (#4258).
As I understand it this issue has never been part of a release since it was introduced due to merging; so we may not need to add it in the readme. But not sure about this, maybe @mpapierski can comment.

2023-11-02 12:28 UTC, alsrdn commented on node/CHANGELOG.md
> +* Add a finer grained latching mechanism for block_synchronization (#4042).
This was part of 1.5.3 and is described below with:
`Remove the `block_synchronizer.stall_limit` node config parameter since it is no longer needed` and `Change the limit of the `core_config.simultaneous_peer_requests` chainspec `

2023-11-02 12:28 UTC, alsrdn commented on node/CHANGELOG.md
> +* Add a NoSync option, which allows a node to opt out of historical sync via config setting (#4257).
I think this should be moved to the `Changed` section and we should mention that the `sync_to_genesis` parameter was replaced with 3 other options:

```
# Historical sync behavior for this node. Options are:
#  'genesis'  (node will attempt to acquire all block data back to genesis)
#  'ttl'      (node will attempt to acquire all block data to comply with time to live enforcement)
#  'nosync'   (node will only acquire blocks moving forward)
```

2023-11-02 12:28 UTC, alsrdn commented on node/CHANGELOG.md
> +* Add more logging in BlockValidator (#4299).
I don't think it's worth mentioning these in the changelog. These were only additional logs to help with debug, but I guess it doesn't hurt to have them here either.

2023-11-02 12:28 UTC, alsrdn commented on node/CHANGELOG.md
> +* Don't return a fatal error when trying to deactivate an era that was already deactivated (#4075).
These were internal fixes that were part of 1.5.3. Should be removed from here.

2023-11-02 12:28 UTC, alsrdn commented on node/CHANGELOG.md
> +* Remove error for timestamp chronology to resolve failing sync (#4195).
This 2 fixes go together. #4195 was a fix for an issue introduced in #4129. I would add a single line to the Readme describing the issue and what was fixed without citing the PRs here.

2023-11-02 12:28 UTC, alsrdn commented on node/CHANGELOG.md
> +* Fix block synchronizer request storm by tweaking the latching (#4205).
This was also part of 1.5.3 and it is an improvement to the `Add a finer grained latching mechanism for block_synchronization PR`. Should be removed from this section.

2023-11-02 12:28 UTC, alsrdn commented on node/CHANGELOG.md
> +* Make the state_identifier parameter of the query_global_state JSON-RPC method optional (#4086).
This is already documented in the line just before this one.

2023-11-02 12:28 UTC, alsrdn commented on node/CHANGELOG.md
> +* Downgrade the 'highest_era_weights does not contain signing_public_key' log message to DEBUG (#4143).
Like in the case of the other debug logging message changes, not sure it is a worthwhile mention but don't have a hard preference here.

2023-11-02 12:34 UTC, alsrdn commented
> @MParlikar there is no changelog for the chainspec AFAIK, but we could add it under the execution engine, because that's where the opcode costs are used (and the PR actually changed the default costs there too: https://github.com/casper-network/casper-node/pull/4387/files)

I think mentioning the default cost changes in the REDME of the EE is a good idea.
We also provide some chainspec examples in the node but not sure if we should actually include this in the node README.

I think it may be best to add a changelog to this repo when the cost changes get merged: https://github.com/casper-network/casper-protocol-release
@MParlikar @jacek-casper WDYT?

2023-11-02 13:41 UTC, jacek-casper commented on execution_engine/CHANGELOG.md
> +* Add initial support for private chain (#3106).
I've gone through them @alsrdn and I noticed that the list right above includes all of the new private chains parameters that I can see (`core.administrators`, `core.fee_handling`, etc)
I'm going to remove this line from the changelog

2023-11-02 13:57 UTC, jacek-casper commented
@alsrdn thanks for the review, I addressed all your comments,
I don't mind adding a changelog in there if that's the best place for production chainspec changes, namely these three things probably need to be mentioned: 
- lower the production gas cost for opcodes ...
- lower the minimum block time to 16 seconds
- lower the upper limit of total gas of all deploys in a block to 4,000,000,000,00

2023-11-02 14:06 UTC, alsrdn approved these changes
LGTM

2023-11-02 15:21 UTC, Fraser999 reviewed
I'd prefer if the PR numbers were removed.  Main reason is down to not being able to apply them consistently, since some PRs will be made to the private repo and can't be found publicly.

If we do end up keeping them, I'd suggest adding actual links, so they become clickable.

2023-11-02 15:21 UTC, Fraser999 commented on execution_engine/CHANGELOG.md
> +* Tweaked upgrade logic transforming withdraw purses to early exit if possible (#4119).
```suggestion
* Tweak upgrade logic transforming withdraw purses to early exit if possible (#4119).
```

2023-11-02 15:21 UTC, Fraser999 commented on execution_engine/CHANGELOG.md
```suggestion



```

2023-11-02 15:21 UTC, Fraser999 commented on node/CHANGELOG.md
> +### Security
Could the order of the sections be made to match the commented example lines above please?

2023-11-02 15:21 UTC, Fraser999 commented on node/CHANGELOG.md
```suggestion


```

2023-11-02 15:21 UTC, Fraser999 commented on types/CHANGELOG.md
> +### Added
Same comment about the section ordering.

2023-11-02 15:21 UTC, Fraser999 commented on types/CHANGELOG.md
```suggestion



```

2023-11-02 15:21 UTC, Fraser999 commented on node/CHANGELOG.md
> +  * The new field `sync_handling` field accepts three values:
```suggestion
  * The new `sync_handling` field accepts three values:
```

2023-11-02 15:54 UTC, jacek-casper commented
@Fraser999 I addressed all the comments, let me know if there's anything else

2023-11-02 17:28 UTC, jacek-casper commented
@mpapierski I've added a mention of `enable_contract_version`, can you have a look and approve?

2023-11-02 17:29 UTC, mpapierski approved these changes

2023-11-02 18:54 UTC, Fraser999 approved these changes
LGTM - thanks for the updates!

2023-11-03 17:15 UTC, jacek-casper commented
bors r+

2023-11-03 19:32 UTC, merged

2023-11-08 14:01 UTC, cspramit commented
The final change logs - https://github.com/casper-network/casper-node/blob/dev/execution_engine/CHANGELOG.md#changed     as a sampling has errors it is showing changed for stuff which was done in past release such as max_stack height 500

2023-11-08 15:57 UTC, jacek-casper commented
@cspramit I didn't remove anything from the Unreleased blocks, because I've assumed they were left there intentionally, I can open another PR removing things that don't appear in the 1.5.3..dev diff