Update changelog entries for modified constants.
casper-network/casper-node pull request #4415
Opened 2023-11-15 14:59 UTC by mpapierski

Follow-up PR for #4387 #4380. This PR adds missing entries in the changelog regarding changed defaults in the code.

2023-11-15 16:35 UTC, jacek-casper approved these changes

2023-11-15 17:10 UTC, AlexanderLimonov requested changes

2023-11-15 17:10 UTC, AlexanderLimonov commented on execution_engine/CHANGELOG.md
> +* Default value for a round seigniorage rate is lowered to `7/175070816`
We should probably mention that this _preserves_ the existing seigniorage per unit of time due to rounds being cut in half

2023-11-16 15:16 UTC, AlexanderLimonov approved these changes

2023-11-16 15:33 UTC, mpapierski commented
bors r+

2023-11-28 12:08 UTC, mpapierski commented
Closing as the changes were cherry picked

2023-11-28 12:08 UTC, closed without merging