Fix several JsonSchema impls and update the schema
casper-network/casper-node pull request #4447
Opened 2023-12-01 13:20 UTC by jacek-casper

Several types generate incorrect schema due to invalid use of the schemars macro attributes, the code was using the `with` attribute, but it doesn't support container types (structs/enums) ([it's documented here](https://github.com/GREsau/schemars/blob/master/docs/1.1-attributes.md#serdewith--type--schemarswith--type)). I've written the impls by hand, there seems to be no way to do it with attributes out of the box.

2023-12-01 14:03 UTC, rafal-ch approved these changes
LGTM :+1:

2023-12-11 12:42 UTC, Fraser999 requested changes
Nice catch on this issue!  However, I have a few suggestions on a slightly different approach for the changes.

2023-12-11 12:42 UTC, Fraser999 commented on types/src/transaction/transaction_v1/transaction_v1_hash.rs
> -)]
I think we could reinstate this, but remove only the `with = "String", ` part, as it's misleading.  Having the generated schema as
```json
      "allOf": [
        {
          "$ref": "#/definitions/Digest"
        }
      ]
```
is ok for this type, as `Digest` is correctly identified as a string type in the schema.

2023-12-11 12:42 UTC, Fraser999 commented on types/src/timestamp.rs
>  pub struct Timestamp(u64);
Seems like the following would produce the same schema:
```rust
#[cfg_attr(
    feature = "json-schema",
    derive(JsonSchema),
    schemars(description = "Timestamp formatted as per RFC 3339")
)]
pub struct Timestamp(#[cfg_attr(feature = "json-schema", schemars(with = "String"))] u64);
```

2023-12-11 12:42 UTC, Fraser999 commented on types/src/transaction/transaction_v1/transaction_v1_hash.rs
> +pub struct TransactionV1Hash(Digest);
This is a good change, but we should probably apply it similarly to `BlockHash` and `DeployHash`.

2023-12-11 15:55 UTC, Fraser999 approved these changes
LGTM - nice work!

2023-12-11 15:59 UTC, Fraser999 approved these changes

2023-12-11 16:39 UTC, jacek-casper commented
bors r+

2023-12-12 13:52 UTC, jacek-casper commented
bors r+

2023-12-12 14:45 UTC, merged