Add test counter to nightly tests script
casper-network/casper-node pull request #4703
Opened 2024-05-08 08:30 UTC by rafal-ch

This PR adds the counter for NCTL nightly tests.

When running, the following output will be available on the console:

`2024-05-08T09:18:19.976460 [INFO] [167839] NCTL :: starting node(s) complete for test #1`

`2024-05-08T09:19:26.774290 [INFO] [167839] NCTL :: starting node(s) complete for test #2`

Please note that the "for test #" suffix is not added if "nctl-start" is invoked from outside the nightly script (when `CASPER_NCTL_NIGHTLY_TEST_COUNT` variable is unset, to be precise).

If all tests finish successfully a summary line is printed at the end:

`All tests passed. Test count: 4`

The counter is incremented inside the `nctl_start.sh` script when it is invoked with the "all" parameter (or no parameter at all). Starting all nodes is a greatest common denominator for all of our nigthly tests, including network soundness test, upgrade tests and nightly tests that use custom setup instead of "start_run_teardown" wrapper. Please keep in mind that this simplification may cause some inconsistencies in the counter if more sophisticated tests are added in the future.

The PR for NCTL repo is here: https://github.com/casper-network/casper-nctl/pull/4

2024-05-08 12:04 UTC, jacek-casper requested changes
I'd rather make this more explicit and put it in `start_run_teardown`, which is used by most tests, and for that don't use `start_run_teardown` we can add a similar wapper, but named `run_without_teardown`, which would just bump the counter.
This way everything could be encapsulated in a single file - `nightly-test.sh`

2024-05-08 13:58 UTC, rafal-ch commented
> This way everything could be encapsulated in a single file - nightly-test.sh
Agreed, it's worth to that in order not to pollute the nctl repo :+1: 
Let me update this.

2024-05-09 11:55 UTC, jacek-casper approved these changes

2024-05-09 12:58 UTC, rafal-ch commented
bors r+

2024-05-09 16:44 UTC, EdHastingsCasperAssociation approved these changes

2024-05-10 12:02 UTC, merged