Added security policy
casper-network/casper-node pull request #4819
Opened 2024-07-31 18:47 UTC by melpadden

Adds an issue template and a SECURITY.md file

2024-08-01 15:50 UTC, sacherjj commented
Supported versions will be outdated.  We should probably push this after we make release-1.5.7 public and update to have 1.5.7 as this version.

2024-08-01 15:54 UTC, sacherjj commented on .github/ISSUE_TEMPLATE/security_vulnerability.yml
> +      placeholder: john@doe.com
Will john@doe.com forward requests to us?

2024-08-01 16:25 UTC, mpapierski requested changes
I have some concerns

2024-11-25 16:26 UTC, mpapierski commented
Closing as discussed on standup

2024-11-25 16:26 UTC, closed without merging