libp2p gossiper
casper-network/casper-node pull request #853
Opened 2021-02-04 11:34 UTC by marc-casperlabs

This PR rips out the old gossiper and replaces it with libp2p's gossiper. It essentially renders the `small_network` component inoperable.

I have tried to keep the refactoring to a minimum and reuse as much of the old structure as possible, to not balloon the scope of this.

2021-02-04 13:48 UTC, goral09 commented on node/src/components/network/behavior.rs
> +            }
I don't think it's a good idea to fail to gossip silently. Consensus, for example, requires for gossiping to work, if we fail to deliver consensus messages silently then the network will stall.

2021-02-04 21:59 UTC, dwerner requested changes
I want to block this because it kills the small_network component.

2021-04-13 20:27 UTC, sacherjj commented
bors ping

2021-04-13 20:35 UTC, sacherjj commented
bors ping

2021-04-13 21:43 UTC, sacherjj commented
bors ping

2021-04-13 21:52 UTC, sacherjj commented
bors ping

2021-04-13 23:44 UTC, sacherjj commented
bors ping

2021-04-28 17:32 UTC, closed without merging